In [2]:
import numpy as np

SISTEMA DE ECUACIONES

In [3]:
#insertar una matriz usando numpy como herramienta
A = np.array([[2,4,6],
             [4,5,6],
             [3,1,-2]])


CALCULAR EL DETERMINANTE

In [ ]:
D = np.linalg.det(A)
D

np.float64(5.999999999999996)

Para hallar los valores de x de un sistema de ecuaciones

In [ ]:
C1 = np.array([[18,4,6],
             [24,5,6],
             [4,1,-2]])
D1 = np.linalg.det(C1)
D1

np.float64(24.000000000000004)

In [ ]:
C2 = np.array([[2,18,6],
             [4,24,6],
             [3,4,-2]])
D2 = np.linalg.det(C2)
D2

np.float64(-12.0)

In [ ]:
C3 = np.array([[2,4,18],
             [4,5,24],
             [3,1,4]])
D3 = np.linalg.det(C3)
D3

np.float64(18.000000000000004)

In [ ]:
X1= D1/D
X2= D2/D
X3 = D3/D

print (X1,X2,X3)

4.0000000000000036 -2.0000000000000013 3.0000000000000027


MATRIZ 8X8

In [ ]:
B = np.array([
    [1, 2, 1, 1, 1, 1, 1, 1],
    [1, 1, 2, 1, 1, 1, 1, 1],
    [1, 1, 1, 2, 1, 1, 1, 1],
    [1, 1, 1, 1, 2, 1, 1, 1],
    [1, 1, 1, 1, 1, 2, 1, 1],
    [1, 1, 1, 1, 1, 1, 2, 1],
    [1, 1, 1, 1, 1, 1, 1, 2],
    [2, 1, 1, 1, 1, 1, 1, 1]
], dtype=float)


TÉRMINOS INDEPENDIENTES DE LA MATRIZ

In [ ]:
b = np.array([16, 15, 14, 13, 12, 11, 10, 17], dtype=float)


CÓDIGO PARA RESOLVER DIRECTAMENTE Y OBTENER LOS RESULTADOS PARA CADA VARIABLE

In [ ]:
Y = np.linalg.solve(B,b)
Y

array([ 5.00000000e+00,  4.00000000e+00,  3.00000000e+00,  2.00000000e+00,
        1.00000000e+00, -7.13714802e-17, -1.00000000e+00, -2.00000000e+00])

PARA LA COMPROBACION

In [ ]:
np.dot(B,Y)

array([16., 15., 14., 13., 12., 11., 10., 17.])

NÚMEROS ALEATORIOS

In [ ]:
rng = np.random.default_rng(seed=123) #El argumento seed determina el estado inicial en el q se va a comenzar
arr = rng.standard_normal((5, 4)) #filasXcolumnas
arr


array([[-0.98912135, -0.36778665,  1.28792526,  0.19397442],
       [ 0.9202309 ,  0.57710379, -0.63646365,  0.54195222],
       [-0.31659545, -0.32238912,  0.09716732, -1.52593041],
       [ 1.1921661 , -0.67108968,  1.00026942,  0.13632112],
       [ 1.53203308, -0.65996941, -0.31179486,  0.33776913]])


AÑADIR ARREGLO CON EDADES DE PERSONAS ADULTAS ENTRE 18 Y 65 AÑOS CON 200 DATOS



In [ ]:
EDADES = np.random.randint(18,66,size=200) #randint pide solo números enteros
EDADES

array([51, 29, 18, 45, 44, 53, 57, 21, 47, 52, 60, 45, 55, 30, 20, 43, 18,
       51, 22, 61, 59, 48, 43, 57, 33, 64, 20, 20, 55, 47, 54, 63, 42, 55,
       51, 57, 23, 53, 54, 25, 31, 34, 49, 62, 30, 48, 42, 39, 48, 54, 25,
       21, 63, 43, 20, 23, 32, 56, 63, 33, 43, 23, 28, 50, 19, 44, 48, 63,
       53, 63, 30, 42, 60, 52, 44, 43, 48, 38, 24, 18, 29, 48, 21, 43, 29,
       47, 64, 47, 45, 21, 48, 41, 60, 51, 33, 39, 39, 65, 34, 33, 64, 56,
       49, 57, 60, 52, 54, 31, 22, 64, 48, 49, 38, 24, 33, 32, 57, 55, 38,
       19, 31, 54, 31, 24, 54, 64, 55, 48, 31, 28, 56, 59, 19, 40, 25, 63,
       25, 29, 58, 46, 30, 24, 39, 27, 35, 60, 56, 56, 20, 25, 32, 43, 27,
       37, 61, 64, 37, 22, 50, 56, 37, 35, 32, 47, 57, 40, 55, 30, 44, 65,
       62, 41, 31, 51, 47, 29, 20, 48, 45, 65, 38, 19, 21, 29, 18, 22, 30,
       51, 63, 28, 43, 51, 26, 36, 31, 36, 48, 38, 39, 40])